


transcrypt.org: 2016-10-03 10:20:50 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 10:20:50 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 10:20:50 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 10:20:50 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 10:20:50 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 10:21:05 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 10:21:21 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 12, in get
    if len (self.json) < 2000:
AttributeError: 'CompilePage' object has no attribute 'json'

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 12, in get
    if len (self.json) < 2000:
AttributeError: 'CompilePage' object has no attribute 'json'
END DEBUG INFO




transcrypt.org: 2016-10-03 10:23:56 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 10:23:56 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 10:23:56 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 10:23:56 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 10:23:56 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 10:24:31 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 14, in get
    if len (self.json) < 2000:
AttributeError: 'CompilePage' object has no attribute 'json'

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 14, in get
    if len (self.json) < 2000:
AttributeError: 'CompilePage' object has no attribute 'json'
END DEBUG INFO

localhost:4000: 2016-10-03 11:03:27 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-03 11:07:24 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:07:24 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:07:24 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:07:24 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:07:24 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




transcrypt.org: 2016-10-03 11:08:51 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:08:51 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:08:51 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:08:51 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:08:51 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 11:08:55 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:08:55 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:09:25 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:09:53 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:12:21 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:12:56 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:13:03 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:15:05 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:15:13 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:16:15 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:16:25 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:21:37 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:22:13 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:22:19 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:22:44 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:23:05 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:23:12 [access] ip: 127.0.0.1, http://localhost:4000/log --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:23:17 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:23:24 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:26:35 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:26:42 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:30:30 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:30:37 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:34:58 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:35:17 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 28, in get
    console.log (22222222)
NameError: name 'console' is not defined

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 28, in get
    console.log (22222222)
NameError: name 'console' is not defined
END DEBUG INFO

localhost:4000: 2016-10-03 11:36:48 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:36:56 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 28, in get
    print (22222222)
NameError: name 'console' is not defined

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 28, in get
    print (22222222)
NameError: name 'console' is not defined
END DEBUG INFO




transcrypt.org: 2016-10-03 11:37:16 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:37:16 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:37:16 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:37:16 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:37:16 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 11:37:24 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:37:30 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 33, in get
    fileNameHead = json.loads (self.json)
AttributeError: 'ExamplePage' object has no attribute 'json'

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 33, in get
    fileNameHead = json.loads (self.json)
AttributeError: 'ExamplePage' object has no attribute 'json'
END DEBUG INFO




transcrypt.org: 2016-10-03 11:42:02 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:42:02 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:42:02 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:42:02 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:42:02 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 11:42:19 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-03 11:43:18 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:43:18 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:43:18 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:43:18 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:43:18 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 11:43:29 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-03 11:45:15 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:45:15 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:45:15 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:45:15 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:45:15 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 11:45:20 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-03 11:45:37 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 11:45:37 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 11:45:37 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 11:45:37 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:45:37 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 11:45:59 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:46:22 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 48, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 86, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 33, in get
    fileNameHead = json.loads (self.json)
AttributeError: 'ExamplePage' object has no attribute 'json'

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 48, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 86, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\transcrypt.org\transcrypt_server.py", line 33, in get
    fileNameHead = json.loads (self.json)
AttributeError: 'ExamplePage' object has no attribute 'json'
END DEBUG INFO

localhost:4000: 2016-10-03 11:48:41 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 11:49:09 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:13:06 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:13:07 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:13:22 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:16:48 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:17:36 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:17:48 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:17:58 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:21:06 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:21:07 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:21:17 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:24:36 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:24:42 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:30:58 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 13:31:04 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-03 14:11:49 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 14:11:49 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 14:11:49 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 14:11:49 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 14:11:49 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 14:12:02 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 14:14:43 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 14:14:59 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-03 15:08:49 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-03 15:08:49 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-03 15:08:49 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-03 15:08:49 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-03 15:08:49 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-03 15:08:55 [access] ip: 127.0.0.1, http://localhost:4000/live/turtle_site --> localhost:4000/live/turtle_site/turtle_site.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-11 11:46:05 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-11 11:46:05 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-11 11:46:05 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-11 11:46:05 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-11 11:46:05 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-11 11:46:25 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-11 16:16:45 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-11 16:16:45 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-11 16:16:45 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-11 16:16:45 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-11 16:16:45 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO




transcrypt.org: 2016-10-11 16:18:16 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-11 16:18:16 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-11 16:18:16 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-11 16:18:16 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-11 16:18:16 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-11 16:18:23 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-11 16:19:39 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 270, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'logoBrown' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 270, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'logoBrown' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation
END DEBUG INFO

localhost:4000: 2016-10-11 16:19:44 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 270, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'logoBrown' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 270, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'logoBrown' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation
END DEBUG INFO

localhost:4000: 2016-10-11 16:19:49 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 270, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'logoBrown' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 270, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'logoBrown' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation
END DEBUG INFO

localhost:4000: 2016-10-11 16:28:34 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-11 16:30:28 [error] Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 267, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'veryTransparenLogoBlue' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation

BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 179, in get
    self.executor (self)
  File "<string>", line 320, in execute
  File "D:\activ_tosh\web\sites\transcrypt.org/static/base.pycss", line 267, in getAll
    background-color: ''' + veryTransparentLogoGreen + ''' ;
NameError: name 'veryTransparenLogoBlue' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\urlMatcher.py", line 120, in callMatching
    return bestUrlPattern [1] (environ, tuple (bestMatch), *(fixedArgs + args), **kwargs)	# May raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 45, in __init__
    self.check ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 83, in check
    self.get () if ok else self.getRedirectToLogin ()
  File "D:\activ_tosh\web\sites\josmith/josmithModules\basePages.py", line 188, in get
    raise notFoundException
Exception: Static file or dir not found: D:/activ_tosh/web/sites/transcrypt.org/static/documentation
END DEBUG INFO

localhost:4000: 2016-10-11 16:40:39 [access] ip: 127.0.0.1, http://localhost:4000/examples --> localhost:4000/live/transcrypt/demos/plotly_demo/plotly_demo.min.html
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-11 17:39:33 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-24 10:35:52 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-24 10:35:52 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-24 10:35:52 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-24 10:35:52 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-24 10:35:52 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-24 10:36:07 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-24 10:36:39 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-24 10:37:55 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-24 10:39:01 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-24 10:39:25 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-24 10:44:17 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




transcrypt.org: 2016-10-31 11:22:28 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

transcrypt.org: 2016-10-31 11:22:28 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

transcrypt.org: 2016-10-31 11:22:28 [message] Python version: 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
BEGIN DEBUG INFO
NoneType
END DEBUG INFO




localhost:4000: 2016-10-31 11:22:28 [initialization] application restarted
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-31 11:22:28 [initialization] table users already exists
BEGIN DEBUG INFO
Traceback (most recent call last):
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 56, in createSuperUser
    self.cs.execute ('CREATE TABLE users (id INTEGER PRIMARY KEY, email_address, password, token)')
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 22, in execute
    raise exception
  File "D:\activ_tosh\web\sites\josmith/josmithModules\db.py", line 14, in execute
    self.cursor.execute (arg1 if arg1 else arg0)
sqlite3.OperationalError: table users already exists
END DEBUG INFO

localhost:4000: 2016-10-31 11:22:52 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-31 12:04:48 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

localhost:4000: 2016-10-31 12:59:00 [access] ip: 127.0.0.1, browser --> localhost:4000/
BEGIN DEBUG INFO
NoneType
END DEBUG INFO

